fix health endpoint
Rookout/terraform-azure-rookout-deployment pull request #20
Opened 2023-04-17 14:47 UTC by idanrookout

2023-04-17 15:19 UTC, idanrookout commented
[RK-18032](https://rookout.atlassian.net/browse/RK-18032)

[RK-18032]: https://rookout.atlassian.net/browse/RK-18032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-18 08:02 UTC, idanrookout commented
@gosharo can you please approve?

2023-04-18 12:58 UTC, gosharo requested changes

2023-04-18 12:58 UTC, gosharo commented on controller-appservice.tf
> +    health_check_path = "/healthz"
@idanrookout not going to work.

2023-04-18 13:01 UTC, closed without merging